### ISSUE TITLE
1.2.3 테스트를 작성해야하는 이유 중 코드 품질 향상을 위한 이유는 무엇일까요? 

### ISSUE THREAD

**Issue by SMJminjeong** [super-ealry-bird/TESTING_FRONTEND#1]
📝 6p

❓ 테스트를 작성해야하는 이유 중 **코드 품질을 향상**하기 위함이 있는데 테스트 코드가 **코드 품질에 어떤 영향을 줄 수 있는지** 간단하게 설명해주세요.

**Comment by immortal-jinkyu** [comment]
테스트 코드를 작성한다면, 단일 책임의 컴포넌트를 작성하고 관리하기 쉬워집니다. 
컴포넌트의 역할 정의가 되어있고 실패한다면 잘못된 컴포넌트 수정이 진행되고 있다는 것🤘

**Comment by kkite6789** [comment]
구현 코드와 테스트 코드를 같이 작성하게 되면 지속적으로 구현코드를 반추하게 되므로 자연스럽게 향상됩니다.
또한 웹접근성을 높이는 데에도 기여합니다.

**Comment by yjlee-c** [comment]
테스트 코드는 구현 코드의 품질을 되돌아보게 합니다. 만약 테스트 코드를 작성하는 것이 어렵다면, 이는 구현 코드가 너무 많은 역할을 하고 있다는 신호일 수 있습니다. 이 경우, 코드를 더 작은 부분으로 나눌 수 있는지 재검토함으로써, 더 좋은 구조와 책임 분리를 가진 코드를 작성할 수 있게 됩니다.

**Comment by yjkim-89** [comment]
테스트 코드를 작성하면서 구현 코드를 반추하게 되므로 자연스럽게 구현 코드 테스트 및 리펙토링이 진행됨

**Comment by SMJminjeong** [comment]
테스트 코드를 작성하면 기존 코드에 대한 재검토나 리팩토링을 진행할 수 있게 됩니다! 힘들더라도 테스트 코드에 습관을 들여보는 것이 좋을 것 같아요
