### ISSUE TITLE
1.2.4 팀 단위 개발에서 원활한 협업을 위해 테스트 코드가 필요한 이유가 무엇일까요?

### ISSUE THREAD

**Issue by kkite6789** [super-ealry-bird/TESTING_FRONTEND#11]
📝 p.7

❓ 테스트 코드는 글로 작성된 문서보다 훌륭한 사양서라고도 합니다. 팀 단위 개발에서 원활한 협업을 위해 테스트 코드가 필요한 이유가 무엇일까요?

**Comment by immortal-jinkyu** [comment]
남이 짠 코드를 직접 넘겨받는건 굉장히 부담스러운 일이죠 이를 많이 해소시켜줍니다!

**Comment by SMJminjeong** [comment]
기술적 오류뿐 아니라 사양서와 테스트 코드를 비교하며 코드를 확인하면 리뷰와 수정을 반복하는 시간도 줄일 수 있어요. 이렇게 수단으로 사용되어 개발자 간 협업이 원활해지도록 도와줍니다.

**Comment by yjlee-c** [comment]
테스트 코드는 기술적 오류 뿐 아니라 사양서대로 구현됐는지 확인할 수 있어 리뷰어의 부담을 덜어주어 개발자 간 협업이 원활해지도록 도와줍니다.

**Comment by yjkim-89** [comment]
글로 작성된 문서보다 테스트 코드로 입력값과 출력값을 확인할 수 있어 서로 간의 이해를 돕습니다

**Comment by kkite6789** [comment]
테스트 코드로 입력값과 출력값을 확인할 수 있으며 리뷰와 수정을 반복하는 시간도 줄여줍니다.
이에 따라 개발자들의 부담을 덜어 주어 원활한 협업을 할 수 있게 해주는 장점이 있네요~
