### ISSUE TITLE
1.2.4 아이스크림 콘과 테스트 피라미드의 특징

### ISSUE THREAD

**Issue by kkite6789** [super-ealry-bird/TESTING_FRONTEND#12]
📝 p.21

❓ 테스트 전략 모델 중 상층부 테스트의 비중이 높은 아이스크림 콘과 테스트 피라미드에 대한 특징에 대해 간단히 서술하시오

**Comment by immortal-jinkyu** [comment]
아이스크림 콘
 - 아이스크림 콘 모양의 테스트 모델로 상층부(E2E)를 중요시 하는 테스트 모델입니다. 
테스트 피라미드
 - 피라미드 모양의 테스트 모델로 하층부(단위테스트)를 중요시 하는 테스트 모델입니다.

-> 테스트 모델 선택에 따라 비용과 안전성이 영향을 받기 때문에 팀에 맞는 모델을 잘 선택해야 합니다.

**Comment by SMJminjeong** [comment]
상층부 테스트 비중이 높은 `아이스크림 콘` 은 운용 비용이 높고 실행시간이 길다는 특징이 있습니다. 반면 하층부 테스트의 비중이 높은 `테스트 피라미드`는 신속성이 높기 때문에 우수한 전략이라고 합니다.

[[관련 링크] ](https://velog.io/@khh180cm/%EC%8B%A4%EC%9A%A9%EC%A3%BC%EC%9D%98-%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%94%BC%EB%9D%BC%EB%AF%B8%EB%93%9C-%EB%B2%88%EC%97%AD)

**Comment by yjlee-c** [comment]
아이스크림 콘은 상층부 테스트의 비중이 높고 운용비용이 높을 뿐 아니라 외부 모듈의 의존성 때문에 불안정한 테스트가 비교적 많아 안티패턴으로 자주 언급됩니다 
테스트 피라미드는 하층부 테스트의 비중이 높을수록 더욱 안정적이고 가성비 높은 테스트가 가능하다는 것이 핵심입니다. 하층부 테스트는 실행 시간이 짧아 신속성이 높고, 신속성이 높기 때문에 자주 실행할 수 있어 안정성이 높다는 특징이 있습니다.

**Comment by yjkim-89** [comment]
아이스크림 콘 모델 : 상층부 테스트 비중으 높아 실행 시간이 깁니다.
테스트 피라미드 모델 : 하층부 테스트 비중이 높아 실행 시간이 짧아 신송성이 높습니다.

**Comment by kkite6789** [comment]
아이스크림 콘 모델 : 
- 상층부 테스트(E2E) 비중이 높음 - 운용 비용이 높고 실행시간이 길다
- 사용자 관점에서의 테스트를 강조

테스트 피라미드 모델 : 하층부 테스트(단위테스트) 비중이 높아 실행 시간이 짧음 
- 실행 시간이 짧아 신속성이 높고, 신속성이 높기 때문에 자주 실행할 수 있어 안정성이 높다
- 사용자 관점에서의 테스트가 부족할 수 있다.

-> 두 모델의 장단점을 고려하여 상황에 맞게 적절한 테스트 전략을 선택하는 것이 중요합니다
