### ISSUE TITLE
3.2.3 테스트 구성 요소 중 테스트명의 특징

### ISSUE THREAD

**Issue by immortal-jinkyu** [super-ealry-bird/TESTING_FRONTEND#13]
📝 p.29-36

❓ 코드 3-7을 기반하여 아래 테스트가 잘못된 이유를 설명하시오
```
test("70 + 80은 100", () =>{
  expect(add(70, 50)).toBe(100);
});
```

**Comment by yjkim-89** [comment]
테스트명 부적합 합니다. 
"70 + 80은 100" 반환 값이 왜 100인지 알 수 없음.

**Comment by sbkimm** [comment]
테스트명이 적합하지 않습니다! 테스트명을 통해서 어떤 의도를 가진 테스트인지 알 수 있어야 합니다.

**Comment by SMJminjeong** [comment]
테스트명은 어떤 의도를 가진 테스트인지 알 수 있도록 명확하게 작성되어야합니다.

**Comment by dl3l3l** [comment]
테스트명이 적절하지 않습니다. `70+80은 100`이 된다는 것은 이해할 수 없는 테스트명으로 적합하지 않으며 테스트명을 함수 기능에 부합하는 이름으로 변경하여야 합니다.

**Comment by immortal-jinkyu** [comment]
왜 100 값이 truly 한지 명확하지 않기 때문입니다. 비즈니스의 요소도 테스트명에 포함되어야합니다.
`각 수를 더하고 100이상의 수는 100으로 고정한다.`  등의 테스트 명이 필요합니다.

비즈니스가 복잡할수록 테스트 이름이 중요한 것 같습니다. 테스트 이름을 정할 수 없다면 리팩토링의 대상이 될 것이라 생각듭니다.

**Comment by kkite6789** [comment]
테스트명만 보고도 어떤 테스트인지 의도를 알 수 있을 정도로 명확한 테스트명이 되어야 합니다.
