### ISSUE TITLE
3.7.4 Reject 검증 테스트

### ISSUE THREAD

**Issue by yjkim-89** [super-ealry-bird/TESTING_FRONTEND#14]
📝 p.50-51

❓ Reject 검증 테스트 우리는 어디에 사용하면 좋을까요?

**Comment by jkyang-c** [comment]
API를 호출하고 오류가 발생하는 상황을 테스트 케이스로 작성할 수 있을 것 같습니다.
예를 들어, 로그인 상황의 케이스를 만들고 오류 상황(중복로그인)을 발생 시킵니다.

오류 응답을 받고 reject하는지 확인합니다.

**Comment by SMJminjeong** [comment]
폼 입력을 한 후 필수 입력 필드 누락에 대한 테스트나 이메일 주소, 전화번호 등의 잘못된 형식이 입력 되었는지 테스트 케이스로 작성해 볼 수 있을 것 같습니다.

**Comment by dl3l3l** [comment]
프로필 이미지나 지식 이미지 등을 업로드할 때, 파일 타입이나 파일 사이즈를 체크하는 테스트 케이스를 작성하여 사용할 수 있을 것 같습니다.

**Comment by sbkimm** [comment]
멤버 아이디 등 고유한 값을 가져야하는 도메인에 대해서 이미 존재하는지 체크하는 로직에 대해 reject 검증 테스트를 적용해 볼 수 있을 것 같습니다.

**Comment by yjkim-89** [comment]
제품 예외 케이스에서 사용 가능

1. 중복 로그인
2. 이메일 전화번호 형식 검사
3. 이미지 파일 타입 검사
4. 고유한 키 이미 존재하는지 체크

**Comment by yjkim-89** [comment]
제품 예외 케이스에서 사용 가능

1. 중복 로그인
2. 이메일 전화번호 형식 검사
3. 이미지 파일 타입 검사
4. 고유한 키 이미 존재하는지 체크

**Comment by kkite6789** [comment]
위의 항목들 뿐만 아니라 validation check가 필요한 영역에서 모두 사용가능합니다.
