### ISSUE TITLE
3.7.5 비동기 처리 테스트에서 assertions이 필요한 이유

### ISSUE THREAD

**Issue by sbkimm** [super-ealry-bird/TESTING_FRONTEND#15]
📝 p.51-52

❓ 아래 코드에서 **expect.assertions** 이 필요한 이유를 설명해주세요

```
test("지정 시간을 기다린 뒤 경과 시간과 함께 reject된다", async () => {
   expect.assertions(1);
   try {
      await wait(50);
   } catch (err) {
      expect(err).toBe(50);
   }
});
```

**Comment by immortal-jinkyu** [comment]
try-catch구문에서 단언문이 실행되지 못합니다. 
이와 같은 실수를 방지하기 위해 단언문의 횟수를 입력하여 호출이 되었는지 검증합니다.

**Comment by yjkim-89** [comment]
expect.assertions 없으면 
await timeout(50); 에서 reject가 발생하지 않아도 테스트 코드는 성공 (사실상 실패해야 하는 케이스)

**Comment by SMJminjeong** [comment]
expect.assertions(1)은 비동기 테스트에서 특정 수의 assertions이 실행되도록 보장하는 데 필요합니다. 
해당 설정을 통해서 assertion이 실행되지 않거나 누락된 경우 혹은 비동기 코드가 예상대로 동작하는지 확인할 수 있기에 필요합니다.

**Comment by dl3l3l** [comment]
catch (err) 뒤에 작성된 단언문에 도달하게 하기 위해 필요합니다. `expect.assertions` 없이 try-catch문의 예외 발생 검증 테스트를 진행하면 단언문이 실행되지 않고 종료되어 테스트는 실패하게 됩니다.

**Comment by sbkimm** [comment]
`expect.assertions`을 통해 단언문의 실행 횟수를 검증할 수 있습니다. 위의 코드에서 expect.assertions을 작성하지 않을 경우 wait 메서드는 오류가 발생하지 않으므로 catch문 안에 있는 단언문이 실행되지 못하고 테스트는 성공으로 끝나게 됩니다. 그리고 이는 의도한대로 테스트가 되지 않기 때문에 올바르지 않은 테스트입니다.

**Comment by kkite6789** [comment]
try-catch구문에서 단언문이 실행되게 하기 위해서 필요하며 의도하지 않은 테스트(wait이 성공으로 끝남)를 방지하기 위해 사용됩니다.
