### ISSUE TITLE
4.1 스텁과 스파이에 대하여(+4.2)

### ISSUE THREAD

**Issue by kkite6789** [super-ealry-bird/TESTING_FRONTEND#22]
📝 p.54~56
❓ 아래 문제 중 한 가지를 골라 간단히 서술해주세요!
(크게 답이 갈리지 않을 이론 문제라 동일한 문제는 피해주세요 😊)

1. 스텁을 사용하는 이유
2. 테스트 코드를 통해 스텁은 어떻게 사용이 되는지?
3. 스파이를 사용하는 이유와 스텁과의 차이점
4. 테스트 코드를 통해 스파이는 어떻게 사용이 되는지?
5. 목 모듈로 의존 중인 모듈의 스텁을 어떻게 만드는지?

**Comment by SMJminjeong** [comment]
### **3. 스파이를 사용하는 이유와 스텁과의 차이점**
**스파이를 사용하는 이유**
- 스파이는 주로 기록하는 용도로 테스트 대상 외부의 출력을 검증할 때 사용합니다.
- 기존 함수의 동작을 변경하지 않고 호출을 감시하거나 모의할 수 있기에 사용합니다.
<br/>

**스텁과 스파이의 차이점**
- 스텁은 테스트 중에 필요한 미리 정해진 응답이나 데이터를 제공하는 데 사용되는 반면 스파이는 실제 객체를 감시하면서 호출 정보를 기록하지만, 객체의 실제 동작은 변경하지 않는다.

**Comment by sbkimm** [comment]
### **1. 스텁을 사용하는 이유**
스텁은 테스트 대상이 의존 중인 컴포넌트에 테스트하기 어려운 부분이 있을 때 이를 대체하기 위해 사용합니다. 주로 테스트 대상이 스텁에 접근하면 정해진 대상을 반환하도록 만듭니다.

**Comment by immortal-jinkyu** [comment]
**5. 목 모듈로 의존 중인 모듈의 스텁을 어떻게 만드는지?**

미완성 혹은 수정이 필요한 모듈에 의존중일 경우 목모듈을 만들어 대체하여 테스트합니다.

**Comment by yjkim-89** [comment]
## 2. 테스트 코드를 통해 스텁은 어떻게 사용이 되는지?

의존 중인 컴포넌트를 대체하거나, 정해진 값을 반환하는 용도

**Comment by dl3l3l** [comment]
**4. 테스트 코드를 통해 스파이는 어떻게 사용이 되는지?**
스파이는 테스트 코드에서 주로 기록하는 용도로 사용하며 테스트 대상 외부의 출력을 검증할 때 사용합니다.

**Comment by kkite6789** [comment]
주관식 문제들이라 완료처리합니다~
