### ISSUE TITLE
5.3.1 테스트할 UI 컴포넌트

### ISSUE THREAD

**Issue by immortal-jinkyu** [super-ealry-bird/TESTING_FRONTEND#23]
📝 p.85~88
❓  아래 테스트에서 실패한 이유를 작성해주세요.

```tsx
test("아래 테스트가 실패 한이유를 작성해주세요", ()=>{
 const mockFn = jest.fn();
 render(<TestForm name="홍길동", nickName="동에번쩍서에번쩍" onConfirm={mockFn}/>);
 expect(screen.getByRole("heading")).toHaveTextContent('홍길동');
 expect(screen.getByText("동에번쩍서에번쩍")).toBeInTheDocument();
 expect(screen.getByRole("button")).toBeInDocument();
})

export const TestForm = ({name, nickName, ticketIds, onConfirm}: ITestFormProps):JSX.Element => {
    return <>
        <h2>{name}</h2>
        <p>{nickName}</p>
        <button onClick={onConfirm}>확인</button>
    </>;
}
```

**Comment by yjkim-89** [comment]
빠르다

1. 쉼표
render(<TestForm name="홍길동", nickName="동에번쩍서에번쩍" onConfirm={mockFn}/>);

2. toBeInDocument 없는 matcher, toBeInTheDocument

기타.
ITestFormProps ticketId는 ticketId?: string; 아니고 ticketId: string; 일 경우 render에 ticketId 부분 추가 필요함.

**Comment by dl3l3l** [comment]
1. `<TestForm name="홍길동", nickName="동에번쩍서에번쩍" onConfirm={mockFn}/>` 에서 잘못된 위치에 콤마가 있어 오류가 발생합니다. 홍길동 뒤에 콤마를 제거하여야 합니다.
2. 테스트 코드 중 `expect(screen.getByRole("button")).toBeInDocument();` 부분에서 존재하지 않는 매처를 사용하였기 때문입니다. `toBeInDocument` 가 아닌 `toBeInTheDocument`로 작성하여야 합니다.

**Comment by sbkimm** [comment]
1. JSX 구문에 잘못된 쉼표
`<TestForm name="홍길동", nickName="동에번쩍서에번쩍" onConfirm={mockFn}/>`
2. matcher명 오류
toBeInDocument(X)  -> toBeInTheDocument(O)

**Comment by immortal-jinkyu** [comment]
test("아래 테스트가 성공하기 위한 컴포넌트를 작성해주세요. 확인 버튼을 누르면 이벤트가 실행됩니다.", ()=>{
    const mockFn = jest.fn();
    render(<TestForm name="홍길동" nickName="동에번쩍서에번쩍" onConfirm={mockFn}  />);
    expect(screen.getByRole("heading")).toHaveTextContent('홍길동');
    expect(screen.getByText("동에번쩍서에번쩍")).toBeInTheDocument();

    const button = screen.getByRole("button");
    expect(button).toBeInTheDocument();

    // fireEvent.click(screen.getByRole("button"));
    expect(mockFn).toHaveBeenCalled();
})

ㅎ..

**Comment by kkite6789** [comment]
`screen.getByRole("button")`을 사용하여 버튼 요소를 찾고 있지만, 
`toBeInDocument() `메서드가 없기 때문입니다.
대신 `toBeInTheDocument()`를 사용해야 합니다.
