### ISSUE TITLE
5.5.2 계정 정보 입력 컴포넌트 테스트

### ISSUE THREAD

**Issue by yjkim-89** [super-ealry-bird/TESTING_FRONTEND#24]
📝 p.97~101
❓ 아래 테스트가 실패한 이유를 설명하고, 테스트가 성공적 할 수 있는 여러 가지 방법을 제시해 주세요.

```tsx
..생략..
   <input type="password" placeholder="8자 이상" />
..생략..

test("비밀번호 입력란", async () => {
  render(<InputAccount />);
  expect(() => screen.getByRole("textbox", { name: "비밀번호" })).not.toThrow();
});
```

**Comment by dl3l3l** [comment]
테스트가 실패한 이유는  `<input type="password"/>` 가 textbox 역할을 가지지 않기 때문에 `screen.getByRole("textbox", { name: "비밀번호" })` 가 비밀번호 입력칸을 찾지 못하기 때문입니다.
테스트가 성공할 수 있도록 하려면 아래와 같이 `getByRole`대신 placeholder 값을 참조하는 `getByPlaceholderText`를 사용하는 것입니다.

``` tsx
test("비밀번호 입력란", async () => {
  render(<InputAccount />);
  expect(() => screen.getByPlaceholderText("8자 이상")).not.toThrow();
});
```

**Comment by sbkimm** [comment]
테스트가 실패한 이유는 `<input type="password"/>` 가 역할을 가지지 않기 때문에 `getByRole("textbox")`로 요소를 취득할 수 없어서 에러가 발생했기 때문입니다. 이렇게 역할이 없는 경우에는 요소를 취득하는 대체 수단으로 `getByPlaceholderText`를 이용하면  `<input type="password"/>` 요소를 취득할 수 있습니다.
```
test("비밀번호 입력란", async () => {
  render(<InputAccount />);
  expect(() => screen.getByPlaceholderText("8자 이상")).not.toThrow();
});
```

**Comment by immortal-jinkyu** [comment]
<input type='password' /> 가 역할을 가지고 있지 않기 때문.

placeholder값을 참조 `getByPlaceholderText`를 활용하여 입력란 취득 가능합니다.

**Comment by kkite6789** [comment]
input 요소의 type이 "password"이면 이는 textbox 역할을 가지지 않기 떄문입니다.
```tsx
test("비밀번호 입력란", async () => {
  render(<InputAccount />);
  expect(() => screen.getByPlaceholderText("8자 이상")).not.toThrow();
});
```

**Comment by yjkim-89** [comment]
1. Placeholder 사용하여 getByPlaceholderText 사용하기.
2. Label을 추가하고 getByLabelText 사용하기
3. data-testid를 추가하고 getByTestId 테스트하기
