### ISSUE TITLE
6.1.1 커버리지에 관하여

### ISSUE THREAD

**Issue by kkite6789** [super-ealry-bird/TESTING_FRONTEND#29]
- npx jest --coverage
다음 명령어를 이용하여 아래의 리포트를 확인할 수 있습니다.

File           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files     |   100.0   |      100     |     100    |     100.   |
test.tsx     |   100.0   |      100     |     100.   |     100    |

이때 
stmts, branch, funds, lines, Uncovered Line 값에 대하여 하나씩만 설명하세요.(선착순)
(책 외에 추가적으로 확인 후 작성하시면 더 좋습니다!)

**Comment by sbkimm** [comment]
### Funcs (함수 커버리지)
함수 커버리지는 구현 파일에 있는 모든 함수가 적어도 한 번은 호출됐는지를 나타내는 지표입니다.

**Comment by yjkim-89** [comment]
## Branch (분기 커버리지)
모든 조건 분기가 적어도 한 번은 실행됐는지 나타낸다. 커버리지를 정량 지표로 사용할 때 중점적으로 활용 하는 핵심 지표다.
try-catch 블록도 분기 커버리지에 포함됩니다.

**Comment by dl3l3l** [comment]
### Stmts (구문 커버리지)
구문 커버리지는 구현 파일에 모든 구문이 적어도 한번을 실행됐는지 나타내는 지표로 테스트에서 실행된 문(statement)의 비율을 측정합니다.
구문 커버리지는 비교적 단순한 개념으로 쉽게 계산이 가능하다는 장점이 있지만, 모든 구문이 실행되었다고 모든 가능한 입력이나 상태가 테스트된 것은 아니므로 다른 커버리지 기준과 함께 사용하여 포괄적인 테스트를 수행하는 것이 좋습니다.

**Comment by immortal-jinkyu** [comment]
**Uncovered Line**(커버되지 않은 라인)
모든지표가 백분율로 나타나지만 해당 라인은 테스트되지 않은 코드의 라인을 표기합니다.
7인경우 7라인, 5-8인경우 5에서 8라인까지 실행되지 않음을 뜻합니다.

**Comment by SMJminjeong** [comment]
### Lines (라인 커버리지)

구현 파일에 포함된 모든 라인이 적어도 한번은 통과됐는지 나타냅니다.

**Comment by kkite6789** [comment]
주관식 문제라 종료처리합니다~
