### ISSUE TITLE
6.2 커러리지 리포트 읽기

### ISSUE THREAD

**Issue by yjkim-89** [super-ealry-bird/TESTING_FRONTEND#31]
![image](https://github.com/user-attachments/assets/53224474-36b2-4744-ba20-2bdd38264d0a)

다음 이미지 수치가 무엇을 의미하는지 설명해주세요. 1개씩.

1. Stmts : 83.33% 5/6
2. Branch : 33.33% 1/3
3. Funcs : 100% 3/3
4. Lines : 83.33% 5/6

**Comment by dl3l3l** [comment]
**2. Branch : 33.33% 1/3**
위 수치는 전체 3개의 조건 분기 중에 1개의 분기만 테스트를 통해 실행됐다는 의미로 
코드 내에 더 많은 분기를 테스트 하지 않은 상태로 리포트에서 빨간색 셀로 나타나며 테스트가 불충분하는 것을 알 수 있습니다.

**Comment by jkyang-c** [comment]
Funcs : 100% 3/3
함수에 대한 코드 커버리지를 나타내며, 코드 내 3개의 함수가 있으며 그 중 3개가 통과하여 100%의 함수가 테스트에 통과했다는 뜻입니다.

**Comment by immortal-jinkyu** [comment]
Funcs : 100% 3/3
함수에 대한 코드 커버리지를 나타내며, 코드 내 3개의 함수가 있으며 그 중 3개가 통과하여 100%의 함수가 테스트에 통과했다는 뜻입니다.

**Comment by sbkimm** [comment]
`Lines : 83.33% 5/6`
구현된 파일에 포함된 6라인 중에서 5라인이 적어도 한 번 통과되었다는 의미입니다.

**Comment by SMJminjeong** [comment]
Stmts : 83.33% 5/6
코드 구문 중 83.33%의 구문이 테스트에 통과되었다는 뜻입니다.

**Comment by kkite6789** [comment]
`Stmts: 3.33% (5/6)`
전체 코드에서 83.33%만큼의 구문이 테스트 되었다는 얘기이며, 즉 1개의 구문이 테스트 되지 않았다는 얘기입니다.
