### ISSUE TITLE
7.5 React Hook Form에서의 제어/비제어 컴포넌트

### ISSUE THREAD

**Issue by immortal-jinkyu** [super-ealry-bird/TESTING_FRONTEND#33]
📝 p.150
❓ 제어 컴포넌트와 비제어 컴포넌트의 차이점은 무엇인가요? React Hook Form을 사용할 때 어떤 경우에 제어 컴포넌트 대신 비제어 컴포넌트를 사용하는 것이 더 적합한지 설명해 주세요.

**Comment by kkite6789** [comment]
제어 컴포넌트 : 컴포넌트 단위로 상태를 관리하는 컴포넌트 ( ex: `useState`를 통한 상태 관리)
비제어 컴포넌트 : 입력 요소에 브라우저 고유 기능을 사용해 값을 집적 참조하도록 구현 (ex: `ref`와 `defaultValue`를 사용)

`defaultValues`를 통해 초기값 설정으로 진행하거나 폼 상태를 업데이트할 필요가 없는 경우에 비제어 컴포넌트를 사용하는 것이 더 효율적입니다.

**Comment by yjkim-89** [comment]
제어 컴포넌트 : `useState` 등을 사용해 상태를 관리하는 컴포넌트
비제어 컴포넌트 : `<input>` 등의 입력 요소에 값을 상태 관리하지 않는 컴포넌트

React Hook Form 는 제어 컴포넌트의 복잡성을 줄이고 성능을 향상시키는 것을 목표로 합니다.

**Comment by dl3l3l** [comment]
`제어 컴포넌트`는 useState을 사용하여 컴포넌트 단위로 state를 관리하고 업데이트하여 사용자가 입력을 취할 때마다 리렌더링을 발생시키는 반면, `비제어 컴포넌트`는 ref를 사용하여 값을 얻어 사용자가 직접 트리거하기 전까지는 리렌더링을 발생시키지 않습니다.
그러므로, **즉각적인 렌더링과 동기화가 필요 없는 경우**에는 비제어 컴포넌트를 사용하는 것이 효율적입니다.

**Comment by SMJminjeong** [comment]
**제어 컴포넌트** : 요소의 상태를 state 로 관리한다.
**비제어 컴포넌트** : 상태를 React 가 제어하는 것이 아닌 DOM 자체에서 직접 관리한다.

`성능 최적화` 가 필요하거나 `입력 폼 상태가 중요하지 않은 입력 필드` 의 경우 **비제어 컴포넌트** 를 사용하는 것이 더 적합합니다.

**Comment by sbkimm** [comment]
- 제어 컴포넌트 : react의 상태(state)를 사용하여 데이터를 관리하는 컴포넌트
- 비제어 컴포넌트 : react의 상태(state)를 사용하지 않고, DOM을 직접 조작하여 데이터를 관리하는 컴포넌트

고성능을 요구하는 컴포넌트는 비제어 컴포넌트로 작성하는 것이 더 적합합니다.

**Comment by immortal-jinkyu** [comment]
제어 컴포넌트: React의 상태로 입력 값을 관리하는 컴포넌트. 상태 변경 시 렌더링이 발생합니다.
비제어 컴포넌트: DOM에서 직접 값을 관리하는 컴포넌트. 렌더링이 줄어들어 성능에 이점이 있습니다.

테스트에 적합한 폼의 초기 상태만 필요하거나, 간단한 폼에서는 비제어 컴포넌트가 더 효율적입니다.
