### ISSUE TITLE
8.1.3 빈칸에 들어갈 알맞은 단어와 해당 단계들에 대해 간단하게 설명해주세요.

### ISSUE THREAD

**Issue by SMJminjeong** [super-ealry-bird/TESTING_FRONTEND#38]
📝 p.179
❓ 모든 스토리에는 `Global` `Component` `Story` 라는 `             ` 방식으로 적용됩니다. 
&nbsp;  &nbsp;    빈칸에 들어갈 알맞은 단어와 세가지 단계에 대해서 간단하게 설명해주세요.

**Comment by sbkimm** [comment]
모든 스토리에는 Global, Component, Story 라는 **`세 단계의 설정이 깊은 병합`** 방식으로 적용됩니다.
* Global 단계 : 모든 스토리에 적용할 설정 (`.storybook/preview.js`)
* Component 단계 : 스토리 파일에 적용할 설정 (`export default`)
* Story 단계 : 개별 스토리에 적용할 설정 (`export const`)

**Comment by dl3l3l** [comment]
모든 스토리에는 Global Component Story 라는 `세 단계의 설정이 깊은 병합` 방식으로 적용됩니다.
* Global 단계 : 모든 스토리에 적용할 설정(.stroybook/preview.js), 우선순위가 제일 낮음
* Component 단계 : 스토리 파일에 적용할 설정(export default)
* Story 단계 : 개별 스토리에 적용할 설정(export const), 우선순위가 제일 높음

**Comment by immortal-jinkyu** [comment]
[깊은 병합]
`Global`: 모든 스토리에 적용 설정
`Component`:  스토리 파일에 적용할 설정
`Story`: 개별 스토리에 적용할 설정

**Comment by kkite6789** [comment]
`세 단계의 설정이 깊은 병합` 방식으로 적용됩니다.

Global : 모든 스토리에 적용할 설정 (.storybook/preview.js)
Component : 스토리 파일에 적용할 설정 (export default)
Story : 개별 스토리에 적용할 설정 (export const)
