### ISSUE TITLE
2.4.2 테스트 전략 모델 중 하나인 테스팅 트로피의 특징에 대해 설명해주세요.

### ISSUE THREAD

**Issue by dl3l3l** [super-ealry-bird/TESTING_FRONTEND#4]
📝 p.22

❓ 비용 분배 최적화에 참고할 수 있는 테스트 전략 모델로 테스팅 트로피가 있습니다. 테스팅 트로피 모델의 특징 및 의도에 대해 설명해주세요.

**Comment by SMJminjeong** [comment]
가장 중요한 핵심은 `통합 테스트 비중` 이 가장 높아야 한다는 것입니다. 단일 UI 컴포넌트로 구현되는 기능은 거의 없고, 사용자 조작을 기점으로 한 통합 테스트 비중이 높을수록 더욱 우수한 테스트 전략이라는 의도가 있습니다.

**Comment by jkyang-c** [comment]
상층부 테스트가 신속성이 떨어지고, 하층부 테스트가 신속하며 중요한 내용들이다라고 주장하는 테스트 피라미드와 반대되는 의견으로 프론트엔드는 사용자가 직접 사용하기때문에 직접 조작하고 동작하는 통합테스트가 중요하여 만들어진 트로피 모델입니다.

**Comment by immortal-jinkyu** [comment]
상층부 테스트가 신속성이 떨어지고, 하층부 테스트가 신속하며 중요한 내용들이다라고 주장하는 테스트 피라미드와 반대되는 의견으로 프론트엔드는 사용자가 직접 사용하기때문에 직접 조작하고 동작하는 통합테스트가 중요하여 만들어진 트로피 모델입니다.

**Comment by kkite6789** [comment]
테스팅 트로피는 각 테스트 카테고리의 상대적인 비중을 시각적으로 나타내기 위해 트로피 모양으로 표현되며
핵심은 통합 테스트의 비중이 가장 높아야 합니다.

**Comment by yjkim-89** [comment]
테스팅 트로피 모델은 통합 테스트 비중이 높으며, 사용자 조작을 기점으로 한 테스트로 프런트엔드 개발에 적합합니다.

**Comment by dl3l3l** [comment]
테스팅 트로피는 통합 테스트 비중이 가장 높은 전략 모델로 사용자 조작을 기점으로 한 통합 테스트 비중이 높을수록 더욱 우수한 테스트 전략이라는 의도가 있습니다.
