### ISSUE TITLE
8.9 스토리를 import 하여 테스트 대상으로 만들어 사용 시 장점

### ISSUE THREAD

**Issue by dl3l3l** [super-ealry-bird/TESTING_FRONTEND#41]
📝 p.208 ~ p 210
❓ 스토리를 통합 테스트에 재사용하여 운용비를 줄일 수 있는데, 테스트에 스토리를 재사용 하려면 필요한 전용 라이브러리가 필요합니다. 해당 라이브러리가 무엇인지 작성하고, @storybook/test-runner와의 차이점을 설명하세요.

**Comment by immortal-jinkyu** [comment]
`@storybook/testing-react` 입니다.
`testing-react`는 이미 정의된 스토리를 불러와 중복을 줄여 테스트 진행이 가능합니다. 이미 정의된 story 코드를 불러와 일관성을 유지할 수 있습니다.
`test-runner`는 직접 테스트를 브라우저에서 육안으로 확인하며 진행하여 실제환경과 유사성이 높습니다. 별도의 테스트 코드없이 동작 가능합니다.

**Comment by SMJminjeong** [comment]
`@storybook/testing-react` 
`testing-react` 는 storybook 에서 정의한 스토리를 재사용하여 UI 컴포넌트의 렌더링과 상호작용을 테스트합니다.
`test-ruuner` 는 브라우저에서 직접 테스트를 수행하여 실제 환경과 유사한 조건에서 테스트합니다.

**Comment by sbkimm** [comment]
테스트에 스토리를 imporot 하려면 `@storybook/testing-react` 라이브러리가 필요합니다.
`@storybook/test-runner` 와의 차이점은 스토리를 재사용하여 중복을 줄일 수 있고 실행 속도가 빠릅니다. 또한, 목 모듈이나 스파이가 필요한 테스트를 작성할 수 있습니다.

**Comment by kkite6789** [comment]
`@storybook/testing-react` 라이브러리를 사용
- `@storybook/testing-react`: React Testing Library와 통합하여 개별적으로 테스트할 수 있는 유틸리티를 제공.
- `@storybook/test-runner`: Storybook 스토리를 자동으로 탐색하고 테스트를 실행하는 도구로, CI/CD 파이프라인에서 유용하게 사용될 수 있음.
