### ISSUE TITLE
8.2 스토리북 필수 애드온

### ISSUE THREAD

**Issue by kkite6789** [super-ealry-bird/TESTING_FRONTEND#42]
스토리북은 컴포넌트 기반 개발을 위한 도구로, 이를 더 강력하게 활용하기 위해 다양한 애드온을 사용할 수 있습니다.
스토리북 필수 혹은 중요하게 사용되는 애드온들에 대하여 하나씩 소개 및 간단하게 설명해주세요.

ex) Controls
- 개발 중에 다양한 props를 실험할 때 매우 유용하며 실시간으로 디버깅 및 조작이 가능

**Comment by immortal-jinkyu** [comment]
`msw-storybood-addon` : 스토리 북에서 웹 API에 의존하는 테스트를 진행하기 위해 MSW를 사용할 수 있도록 제공되는 addon입니다.

**Comment by SMJminjeong** [comment]
`Actions` 
내부 로직을 처리할 때 Props 로 전달받은 이벤트 핸들러가 호출되는 경우 어떻게 호출됐는지 로그를 출력한다.

**Comment by dl3l3l** [comment]
`Docs`
작업해둔 코드를 바탕으로 해당 컴포넌트의 각 상태별 코드를 show/hide code 버튼을 통해 파일을 찾아 들어가지 않아도 바로 확인하여 작업 가능하며, 어떤 옵션 값들이 있는지 테이블로 설명이 되어 있어 협업 시 유용하게 사용 가능합니다.

**Comment by sbkimm** [comment]
`@storybook/addon-viewport`
반응형으로 구현된 UI 컴포넌트를 확인하기 위해 스토리별로 viewport를 설정할 수 있다.
