### ISSUE TITLE
2.3 프런트엔드 테스트의 목적에 대하여 설명해주세요.

### ISSUE THREAD

**Issue by SMJminjeong** [super-ealry-bird/TESTING_FRONTEND#5]
📝 p.18 -20

❓ 프런트엔드 테스트의 목적에는 3가지 정도 있습니다. 각 테스트 에 대한 간략한 설명을 해주세요.

**Comment by jkyang-c** [comment]
**기능테스트**
- 사용자가 조작할 UI 컴포넌트가 주요 개발 대상이며, 인터랙션 테스트가 주입니다.
- 가상브라우저 테스트로 가능하지만 불가능할경우 실제 브라우저를 통해 진행합니다.
**비기능테스트**
- 비기능 테스트는 소프트웨어의 성능, 보안, 사용성, 접근성 등을 평가하는 테스트 유형입니다. 여기서 접근성(a11y) 테스트는 중요한 비기능 테스트 중 하나로, 웹 애플리케이션이 다양한 사용자, 특히 장애가 있는 사용자들이 사용할 수 있도록 보장하는 것을 목표로 합니다.
**시각적회귀테스트**
- UI의 일관성을 유지하여 코드 변경 후 빠른 피드백을 얻을 수 있어 오류를 예방할 수 있습니다.

**Comment by immortal-jinkyu** [comment]
기능테스트

사용자가 조작할 UI 컴포넌트가 주요 개발 대상이며, 인터랙션 테스트가 주입니다.
가상브라우저 테스트로 가능하지만 불가능할경우 실제 브라우저를 통해 진행합니다.
비기능테스트
비기능 테스트는 소프트웨어의 성능, 보안, 사용성, 접근성 등을 평가하는 테스트 유형입니다. 여기서 접근성(a11y) 테스트는 중요한 비기능 테스트 중 하나로, 웹 애플리케이션이 다양한 사용자, 특히 장애가 있는 사용자들이 사용할 수 있도록 보장하는 것을 목표로 합니다.
시각적회귀테스트
UI의 일관성을 유지하여 코드 변경 후 빠른 피드백을 얻을 수 있어 오류를 예방할 수 있습니다.

**Comment by kkite6789** [comment]
기능 테스트
- SW의 특정 기능이 요구사항에 맞게 동작하는지 확인하는 테스트
- 사용자 요구사항과 비즈니스 프로세스를 기반으로 테스트 케이스를 작성

비기능 테스트
- 기능 외적인 품질 속성을 검증하는 테스트
- 시스템의 성능, 확장성, 안정성, 보안성 등 주로 시스템의 한계와 약점을 찾는데 집중

시각적 회귀 테스트
- SW의 UI 변경이 기존의 시각적 디자인에 영향을 끼쳤는지 확인하는 테스트

**Comment by yjlee-c** [comment]
- 기능 테스트(인터랙션 테스트)
  - 개발된 기능에 문제가 없는지 검증하는 테스트
  - 웹 프론트엔드의 대부분 기능은 UI 컴포넌트 조작(인터랙션)에서 시작하기 때문에 중요도가 높음
- 비기능 테스트(접근성 테스트)
  - 신체적, 정신적 특성에 따른 차이 없이 동등하게 제품을 사용할 수 있는지 검증하는 테스트
  - 검증 항목에 알맞은 적절한 테스트 도구를 사용
- 시각적 회귀 테스트
  - 특정 시점을 기준으로 전후 차이를 비교하여 문제가 있는지 검증하는 테스트
  - 회귀 테스트 중 하나로 헤드리스 브라우저에 그려진 내용을 캡처하여 캡처된 이미지 간 차이를 검증하는데, 사용자 조작으로 변경된 화면까지 캡쳐하여 비교함

**Comment by yjkim-89** [comment]
인터랙션 테스트
 - 웹 어플리케이션에서 UI 컴포넌트가 상호작용할 때 발생할 수 있는 다양한 시나리오를 검증하는 테스트
접근성 테스트
 - 장애를 가진 사용자나 다양한 환경에서 애플리케이션을 사용하는데 불편함이 없는지 검증하는 테스트
시각적 회귀 테스트
 - 특정 시점을 기준으로 전후 차이를 검증하는 테스트

**Comment by SMJminjeong** [comment]
인터랙션 테스트와 비기능 테스트, 시각적 회귀 테스트가 있습니다 ! (설명 생략)
