### ISSUE TITLE
2.2.1 프론트엔드 테스트 범위인 정적테스트란 무엇일까요? 

### ISSUE THREAD

**Issue by immortal-jinkyu** [super-ealry-bird/TESTING_FRONTEND#9]
📝 p.14

❓ 정적테스트에 대해 설명해주시고, DWorks에서 진행하고있는 정적분석엔 무엇이있을까요

**Comment by SMJminjeong** [comment]
정적 분석이란 버그를 야기할 수 있는 코드 스멜을 찾아내어 문제의 소지가 있는 코드를 사전에 수정하는 것을 의미합니다. 현재 진행하고 있는 정적분석에는 `ESLint` 가 있습니다. 

찾다보니 공유하면 좋을 것 같아요! 
https://5kdk.github.io/blog/2023/11/26/eslint-deep-dive

**Comment by kkite6789** [comment]
정적 테스트는 주로 코드의 품질, 일관성, 잠재적인 오류를 사전에 발견하는 것에 큰 목적을 두고 있으며
개발 초기에 문제를 발견하고 수정하는 데 매우 유용한 테스트입니다.

DWorks에서 진행하고있는 정적분석은 인텔리제이 플러그인으로 사용중인 Prettier와 정적분석 도구 SonarQube를 사용하고 있습니다.
저희끼리 진행하는 코드 리뷰도 이에 해당합니다~

**Comment by yjlee-c** [comment]
정적 테스트는 소프트웨어를 실행하지 않고 테스팅하는 기법으로 버그를 조기에 발견할 수 있도록 합니다.
DWorks에서 진행하고 있는 정적 분석은 ESLint, Sonarqube가 있습니다~!

**Comment by yjkim-89** [comment]
애플리케이션을 실행하지 않고 결함을 분석하는 방법
DWorks에서는 ESLint, Sonarqube 코드리뷰가 있습니다.

**Comment by immortal-jinkyu** [comment]
실행전에 할 수있는 테스트를 일컷는데요 저희는 개발 단계 컴파일/빌드 과정에서 이를 진행하게됩니다.
사용중인 정적분석 툴로는 ESLint, Prettier, Sonarquebe 가 있고 항상 진행하는 코드리뷰도 있습니다!
